version: "3.9"
services:
db:
image: postgres:16
environment:
POSTGRES_USER: app
POSTGRES_PASSWORD: app
POSTGRES_DB: app
ports: ["5432:5432"]
volumes: ["pgdata:/var/lib/postgresql/data"]


redis:
image: redis:7
ports: ["6379:6379"]


backend:
build: ./backend
env_file: ./.env
depends_on: [db, redis]
ports: ["8000:8000"]
volumes: ["./backend:/app", "models:/models"]
command: ["bash","-lc","python manage.py migrate && gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000"]


worker:
build: ./backend
env_file: ./.env
depends_on: [backend, redis]
volumes: ["./backend:/app", "models:/models"]
command: ["celery","-A","config","worker","-l","INFO"]


frontend:
build: ./frontend
environment:
- VITE_API_BASE=http://localhost:8000
ports: ["5173:5173"]
volumes: ["./frontend:/app"]


volumes:
pgdata:
models: