# Generated by Django 5.0.6 on 2025-08-31 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('impression', 'impression'), ('view', 'view'), ('click', 'click'), ('add_to_cart', 'add_to_cart'), ('purchase', 'purchase'), ('rating', 'rating')], max_length=32)),
                ('value', models.FloatField(blank=True, null=True)),
                ('context', models.JSONField(default=dict)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
    ]
